# try to find 3rdParty directory
# Include(Find3rdParty)

# packages
FIND_PACKAGE ( Bullet  			REQUIRED )

IF (NOT SLON_ENGINE_CONFIGURE_INTRUSIVE)
	FIND_PACKAGE ( SlonEngine   REQUIRED )
ENDIF (NOT SLON_ENGINE_CONFIGURE_INTRUSIVE)

SET (BOOST_COMPONENTS serialization unit_test_framework)
IF (WALKER_YARD_USE_PYTHON)
	LIST (APPEND BOOST_COMPONENTS python)
ENDIF (WALKER_YARD_USE_PYTHON)

IF (WALKER_YARD_USE_LAPACK)
	FIND_PACKAGE ( Lapack	REQUIRED )
ENDIF (WALKER_YARD_USE_LAPACK)

FIND_PACKAGE ( Boost 1.45.0 REQUIRED COMPONENTS ${BOOST_COMPONENTS} )

# Documentation
FIND_PACKAGE ( Doxygen )
